development:
  adapter: mysql2
  database: twaddle_dev
  pool: 5
  timeout: 5000
  username: root
  password: abc123

test:
  adapter: mysql2
  database: twaddle_test
  pool: 5
  timeout: 5000
  username: root
  password: abc123

production:
  adapter: mysql2
  database: twaddle_prod
  pool: 5
  timeout: 5000
  username: root
  password: abc123
