development:
  adapter: mysql2
  database: twonversations_dev
  pool: 5
  timeout: 5000
  username: root
  password: abc123

test:
  adapter: mysql2
  database: twonversations_test
  pool: 5
  timeout: 5000
  username: root
  password: abc123

production:
  adapter: mysql2
  database: twonversations_prod
  pool: 5
  timeout: 5000
  username: root
  password: abc123
